### ISSUE TITLE
Check file caching

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#179] opened 2017-08-29 15:33 UTC
Sometimes source files are not recompiled although they are changed.

**Comment by dweindl** [comment] 2017-08-30 10:46
The current way of checking the hashes of *.cpp and *.h doesn't work reliably. 

When headers are found to have changed, amici base files are recompiled, the header hashes are updated,  and the current model will be recompiled. However, for the next model it will look as if the files did not change and model sources won't be recompiled, potentially making matlab crash. 

We would need the hashes for the header files in each model directory, or we need to check for last modification date. Preferences or other ideas?

**Comment by FFroehlich** [comment] 2017-08-30 12:01
As soon as we fix #130 this should no longer be necessary. Just disable caching until then?

**Comment by dweindl** [comment] 2017-08-30 12:47
Fixing that will reduce the chance of breaking something, but we will still have some dependencies left. I think we will have to change something anyways. (Something simple, I don't want to reimplement make...)

**Comment by FFroehlich** [comment] 2017-08-30 13:31
True, for the model specific functions that are passed back to the solver it will be tricky to get rid of dependencies on tempdata. We could simply add hashes for the header files to modelname_funname_osname.md5 files and also check for them in checkHash.

**Comment by dweindl** [comment] 2017-11-12 20:41
After changing the model file (sym.p) and running amiwrap() on a previously amiwrap()ed model , the following files have not been regnerated when they should have been:  
``` 
        _JB.cpp
        _JDiag.cpp
        _JSparse.cpp
        _JSparseB.cpp
        _Jv.cpp
        _JvB.cpp
        _dydx.cpp
        _xBdot.cpp
```

**Comment by FFroehlich** [comment] 2017-11-12 23:17
_JB.cpp
        _JDiag.cpp
        _JSparse.cpp
        _JSparseB.cpp
        _Jv.cpp
        _JvB.cpp
        _dydx.cpp
        _xBdot.cpp

are probably due to the fact that `J` does not have a direct dependence on `p` but only on `xdot`. If `xdot` does not change but `p` does, they will not be recompiled. However, I would claim that this is working as intended as long `xdot` did in fact remain the same (if `xdot` did not change `dxdotdx` will be the same, independent of `p`). The same logic basically applies to `dydx`, where `xdot` is replaced by `y`.

Could it be that changes such as reordering are hidden due to renaming of variables?

**Comment by dweindl** [comment] 2017-11-21 09:49
`xdot` did remain the same. Which renaming are you referring to? Is that independent of the parameter ordering in `p`? Can we add an explicit dependency of `J` on `p`? This would create less overhead than debugging models with scrambled parameters.

**Comment by FFroehlich** [comment] 2017-11-21 17:58
No I suspect that the parameter ordering in `p` is in fact the problem. It kind of makes sense and if that is indeed the case, we should probably always recompile if `x`, `k` or `p` change.

**Comment by FFroehlich** [comment] 2017-11-21 18:02
As soon as https://github.com/ICB-DCM/AMICI/pull/222 is merged, the whole dependency thing will be a bit more transparent as dependencies are all explicitely contained in the function signature and we can explicitely extract those. Then we only need to specify this for intermediate symbolic expressions which should be far easier to manage.

**Closed** 2018-01-29 14:09 UTC
